version: '3.8'

services:
  # 1. Сервер локальной LLM (CPU-версия)
  llm_server:
    image: ghcr.io/abetlen/llama-cpp-python:latest
    ports:
      - "8000:8000"
    volumes:
      # Прокидываем только папку с весами (конфиг нам больше не нужен)
      - ./vision/cpp_llm/bin:/app/models
    # ЗАДАЕМ НАСТРОЙКИ ПРЯМО ЗДЕСЬ (они перекроют любые другие)
    environment:
      - MODEL=/app/models/ZwZ-8B-Q6_K.gguf
      - CLIP_MODEL_PATH=/app/models/ZwZ-8B.mmproj-Q8_0.gguf
      - N_GPU_LAYERS=0
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped

  # 2. Наш Оркестратор и Web-API
  api_server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Прокидываем папки для видео и результатов
      - ./_download:/work/lenta_cv/_download
      - ./_output:/work/lenta_cv/_output
    environment:
      # Указываем нашему API, где искать LLM внутри сети Докера
      - LLM_BASE_URL=http://llm_server:8000/v1
    depends_on:
      - llm_server
    restart: unless-stopped